revised code
error due to index range wrong, need to use true_max_num

MacBook-Air:gap_fill_make sunnyair$ python3 gap_fill_021918_1.py
Traceback (most recent call last):
  File "gap_fill_021918_1.py", line 264, in <module>
    analyze_files(user_input_folder,filename_list_f,file_path_list,file_dict_master)
  File "gap_fill_021918_1.py", line 219, in analyze_files
    check_numbering(filename_list,file_path_list,prefix_regex2,file_dict_master)
  File "gap_fill_021918_1.py", line 191, in check_numbering
    fix_numbering(proc_file_list,proc_filePath_list,regex)
  File "gap_fill_021918_1.py", line 237, in fix_numbering
    next_filename = proc_file_list[current_filename_index + 2] # add + 2 so that we get the index position of the next file
IndexError: list index out of range
MacBook-Air:gap_fill_make sunnyair$